mohamed

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,8 +1,28 @@
 #!/usr/bin/env bash
 # script that transfers a file from our client to a server
 # takes 4 paramters
-if [ $# -lt 3 ]; then
+if [ $# -lt 4 ]
+ then
 	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
-	exit 1
+
+	exit 
 fi
-scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/$1
+#assigning paramentals to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# disabbling strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file""p$username@$1p:~/"
+
+
+#checking if the transfer was successful
+if [ $? =eq 0 ]
+then 
+       echo "FILE WAS TRANSFERED SUCCESSFULLY"
+else
+       echo "FILE TRANSFER FAILD"
+fi
